name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create GitHub issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available token
        INPUT_TITLE: "Test Issue"
        INPUT_BODY: "This is a test issue created via GitHub Action."
        INPUT_LABELS: "bug,help wanted"
        INPUT_ASSIGNEES: "user1,user2"
      run: python github_issue.py