name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Manual Approval
      uses: thomasvjoseph/manual-approval@v1.0.1
      with:
        INPUT_TIMEOUT: 10
        INPUT_ASSIGNEES: "murshid-jiitak,JAMES084"
        INPUT_MIN_APPROVERS: "2"

    - name: Run a one-line script
      run: echo Hello, world!
